feat: gui and css to the surgical history view
SanitasUVG/Sanitas pull request #129
Opened 2024-06-21 18:28 UTC by lemoonchild

# Jira

[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-156?atlOrigin=eyJpIjoiZjE3YjU2YTY0MzgxNDc5Mjg5YzhjOTJmMjgxZjRlZGYiLCJwIjoiaiJ9)

## Descripción

Funcionamiento y estilos para la página de antecedentes quirúrjicos. 

## Tasks

- \[x] Asignate a tí mismo dentro de la PR.
- \[x] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x] Agrega el link al issue de Jira.
- \[x] Asegurate que la PR pase todos los chequeos de CI.
- \[x] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-06-22 01:33 UTC, ElrohirGT requested changes
En su mayoría joya aunque si hay cosas que arreglar.

De paso aprovecha a quitarle el alert en la pestaña de `AddPatient`! Porque ahora que ya tiene los estilos bonitos no debería de tener alerts...

2024-06-22 01:33 UTC, ElrohirGT commented on sanitas_frontend/src/components/AppointmentSurgeryCard/index.stories.jsx
> +  title: "Components/Card",
El nombre debería ser el mismo que el del componente, osea `AppointmentSurgeryCard`

2024-06-22 01:33 UTC, ElrohirGT commented on sanitas_frontend/src/dataLayer.mjs
> +  }
estos métodos deberían de seguir las mismas convenciones que los otros, retornando `{restult}` cuando es satisfactorio y `{error}` cuando no lo es.

2024-06-22 01:33 UTC, ElrohirGT commented on sanitas_frontend/src/router.jsx
> +    element: <Outlet />,
Buena idea! Pero tienes que agregar una ruta index! Sino vas a romper la navegación en todas las otras rutas...

https://reactrouter.com/en/main/route/route#index

En este caso la ruta index debería ser la de general information!

2024-06-22 01:33 UTC, ElrohirGT commented on sanitas_frontend/src/router.jsx
> +      },
Esto es la ruta index? Creo que hay que decirle explícitamente con la prop de index.

2024-06-22 01:33 UTC, ElrohirGT commented on sanitas_frontend/src/views/Antecedents/Surgical/index.jsx
> +  }, [id, getSurgicalHistory]);
![image](https://github.com/SanitasUVG/Sanitas/assets/45268815/8950394a-05ac-43d0-9056-c1def77b7e3e)

2024-06-22 01:33 UTC, ElrohirGT commented on sanitas_frontend/src/views/Antecedents/Surgical/index.jsx
> +  };
Ok me estoy dando cuenta, que tus alerts los estás tomando como reemplazo del `console.log`. Esto no se debe hacer, imaginate que Amazon te tirara un Alert cuando compras tus productos diciendote: "Producto comprado exitosamente!". Te quedarías modo 😕 .

Por favor quita los alerts y deja el mensaje de error normal.

2024-06-22 18:00 UTC, lemoonchild commented on sanitas_frontend/src/views/Antecedents/Surgical/index.jsx
> +  }, [id, getSurgicalHistory]);
JAJAJAJAJAA PERDÓN NO ME DI CUENTA

2024-06-26 18:12 UTC, ElrohirGT requested changes
<img width="1407" alt="image" src="https://github.com/SanitasUVG/Sanitas/assets/45268815/1589348d-5070-4c0a-ad1c-c33531a54a9d">

Cuando busco a Maria y navego a los antecedentes quirúrgicos me aparece esto cuando están vacíos...

2024-07-16 19:53 UTC, ElrohirGT requested changes
Esta bien joya la interfaz! Lo único malo que le encontré es que las cirugías cuando las doctoras añadan más deberían de salir en orden del año! Posiblemente haya que poner un ORDER BY en el backend y también en el cliente para arreglar esto...

<img width="1434" alt="image" src="https://github.com/user-attachments/assets/ed705eae-8f8e-46ba-a90a-93d9da70a4a7">

2024-07-17 22:39 UTC, ElrohirGT approved these changes
Ta joya, ya vino mi profe asi que ni podre usar mi telefono o laptop.

2024-07-18 01:05 UTC, merged