feat: added familiar traumatological get put methods
SanitasUVG/Sanitas pull request #143
Opened 2024-07-16 23:17 UTC by XavierLopez25

# Jira

[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-203)

Se agregaron los endpoints de PUT y GET para la obtención y actualización/inserción para los antecedentes familiares y traumatológicos del paciente.

## Tasks

- \[x] Asignate a tí mismo dentro de la PR.
- \[x] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x] Agrega el link al issue de Jira.
- \[x] Asegurate que la PR pase todos los chequeos de CI.
- \[x] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-07-17 21:58 UTC, ElrohirGT requested changes

2024-07-17 21:58 UTC, ElrohirGT commented on sanitas_backend/src/handlers/GetFamilyHistory/get-family-history-patient.integration.test.mjs
> +  });
Cuando el endpoint recibe una ID no válida debería retornar 200 y el default state. Osea, para las datas que son array, simplemente un array vacío.

2024-07-17 21:58 UTC, ElrohirGT commented on sanitas_backend/src/handlers/GetFamilyHistory/get-family-history-patient.mjs
> +    }
Recuerda que cuando se busca un paciente que no existe entonces debe retornar 200 y la data debe tener sus valores por defecto, por ejemplo los arrays deberían ser arrays vacíos.

2024-07-17 21:58 UTC, ElrohirGT commented on sanitas_backend/src/handlers/GetTraumatologicalHistory/get-traumatological-history-patient.integration.test.mjs
> +  });
Igual que las otras, esta no debería retornar 404 sino 200 y la data debería ser la por defecto.

2024-07-17 21:58 UTC, ElrohirGT commented on sanitas_backend/src/handlers/GetTraumatologicalHistory/get-traumatological-history-patient.mjs
> +    }
Retorna data por defecto cuando la ID no existe...

2024-07-17 23:14 UTC, XavierLopez25 commented on sanitas_backend/src/handlers/GetFamilyHistory/get-family-history-patient.integration.test.mjs
> +  });
Sí, casi todos están así porque los cambios a ese estándar de los defaultValues está en la otra PR. Básicamente no tenía donde poner eso sin tener conflicts heavy.

2024-07-19 00:40 UTC, ElrohirGT approved these changes
![image](https://github.com/user-attachments/assets/945f3147-cac1-4c3a-97f5-7d6be4204bb9)

2024-07-19 00:45 UTC, merged