Feat allergic view enpoint
SanitasUVG/Sanitas pull request #169
Opened 2024-08-09 05:42 UTC by DanielDubon

# Jira

[Link al issue en Jira](Link%20al%20clickup)

## Descripción

## Tasks

- \[ \] Asignate a tí mismo dentro de la PR.
- \[ \] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[ \] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[ \] Agrega el link al issue de Jira.
- \[ \] Asegurate que la PR pase todos los chequeos de CI.
- \[ \] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-08-11 15:50 UTC, lemoonchild requested changes
Los cambios que te pedí de la PR de psiquiátricos tomalos para aquí de lo de alérgicos JAJAJAJA se me fue la onda

2024-08-11 19:51 UTC, ElrohirGT requested changes
Arreglá el tema de estilos que te comentó Nahomy en la otra PR y casi estaría ya. Lo único extra que aportaría yo es que no te funes la version! Cuando se hace la request, la alergia que agrego ya solamente tiene un `data` y no el campo de `version`.

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/92e71b0b-59a8-43b9-b0c5-2ada81cd8aae">

2024-08-13 16:38 UTC, ElrohirGT submitted a review, later dismissed
De mi parte ya no hay quejas!

2024-08-13 17:11 UTC, lemoonchild submitted a review, later dismissed
De mi parte también autorizo solo arregla los merge conflicts que dieron JAJAJA

2024-08-14 00:47 UTC, ElrohirGT requested changes
Anda jodido... No me aparece ninguna reacción cuando ingreso una alergia

<img width="1552" alt="image" src="https://github.com/user-attachments/assets/bf59406b-ec15-4ec9-9d36-3ccb9cdc6f7d">

2024-08-14 02:39 UTC, ElrohirGT approved these changes
I approb

2024-08-14 02:39 UTC, merged