Feat psychiatric view endpoint
SanitasUVG/Sanitas pull request #171
Opened 2024-08-11 05:08 UTC by DanielDubon

# Jira

[Link al issue en Jira](Link%20al%20clickup)

## Descripción

Endpoints del update y el get para datos psiquiatricos

## Tasks

- \[ ] Asignate a tí mismo dentro de la PR.
- \[ ] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[ ] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[ ] Agrega el link al issue de Jira.
- \[ ] Asegurate que la PR pase todos los chequeos de CI.
- \[ ] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-08-11 15:44 UTC, lemoonchild requested changes
Solo pequeños cambios al menos de mi parte y trunca owo 

Pero si sería de revisar que la versión también salga en el JSON al momento de guardar la data.

2024-08-11 15:44 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Allergic/index.jsx
> +	console.log("Allergic History Result:", allergicHistoryResult);
Se fue un console log

2024-08-11 15:44 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Allergic/index.jsx
> +							Registro de antecedentes Alérgicos
Me vas a matar, ¿Pero podrías poner el "Alérgicos" como "alérgicos"?

2024-08-11 15:44 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Allergic/index.jsx
> +						text="Agregar antecedente Alérgico"
Aquí también lo mismo kajsdjk de "Alérgicos" a "alérgicos"

2024-08-11 15:44 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Allergic/index.jsx
> +		{ label: "Cambio Climático", value: "climateChange" },
¿No sería mejor cambio de clima? Es que cambio climatico suena gracioso JAJAJAJ

2024-08-11 15:44 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Allergic/index.jsx
> +	const handleSaveNewAllergie = async () => {
Estaba viendo que hay un error al guardar 

![image](https://github.com/user-attachments/assets/cf2893e8-c689-458b-9625-bca6f39ef12e)

Debe de aparecer la versión al guardar también, no solo la data, sería algo de revisar y arreglar

2024-08-11 18:55 UTC, DanielDubon commented on sanitas_frontend/src/views/History/Allergic/index.jsx
> +		{ label: "Cambio Climático", value: "climateChange" },
no

2024-08-11 19:46 UTC, ElrohirGT requested changes
Los endpoints en sí los veo bien. Por favor ahí te funas los cambios que le hiciste al frontend porque esta PR solamente debería de cambiar el backend...

2024-08-12 01:06 UTC, ElrohirGT commented
Se me olvidó ponertelo en la review pero tenés el mismo clavo que tuvo @BiancaCalderon en una PR anterior. Te faltó agregarle documentación! Ahí se la pones porfa a tu endpoint... Tenés que irte al archivo (de la DB)[https://github.com/SanitasUVG/Sanitas/blob/develop/wiki/mantenimiento/db/README.md] y agregar ahí tu versión y el formato de los datos que guardas...

Me contas si te da duda después de revisarlo!

2024-08-12 06:53 UTC, closed without merging