feat: git init base UI was made(only base UI working PRE BETA)
SanitasUVG/Sanitas pull request #190
Opened 2024-08-24 02:05 UTC by DanielDubon

# Jira

[Link al issue en Jira](Link%20al%20clickup)

## Descripción

## Tasks

- \[ \] Asignate a tí mismo dentro de la PR.
- \[ \] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[ \] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[ \] Agrega el link al issue de Jira.
- \[ \] Asegurate que la PR pase todos los chequeos de CI.
- \[ \] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-08-26 00:18 UTC, lemoonchild requested changes
Al botón de agregar medicamento al añadir uno debería de tener la opción de cancelar el medicamento. 

![image](https://github.com/user-attachments/assets/cac17c90-29bf-4429-9975-e3c9d10979dc)

El de cancelar debe de ser blanco y el de agregar debe de ser el verde. 

------------------------------------------------------------------------------
Otra cosa: 

![image](https://github.com/user-attachments/assets/fa45b6e7-cb86-4018-9769-707c7665c340)

Hay mucho espacio entre el botón de editar y el demás contenido. 

------------------------------------------------------------------------------

Tercero, al momento de guardar deberías de volver a recargar la página pq se buguea al momento de guardar, tengo que salir y volver a entrar a a la vista para que aparezca el botón (esto lo hago en no patológicos para tener una idea)

![image](https://github.com/user-attachments/assets/eaf69791-e5ea-4065-ac1a-95c4771a0f46)

Esto también aplica al editar. 

------------------------------------------------------------------------------

Otra cosa: 

Al momento de cancelar la edición debería de hacer reset a los datos originales (esto lo tengo en PR de no patológicos para tener una idea)

------------------------------------------------------------------------------

Te falta la info de los placeholders: 

La del medicamento: Ingrese el medicamento administrado (terapia entra en la categoría)
La de la dosis: Ingrese cuánto (opcional)
La de la frecuencia: Ingrese cada cuánto administra el medicamento


------------------------------------------------------------------------------

Esto es lo que veo por el momento je

2024-08-26 00:18 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Psichiatric/index.jsx
>  								<BaseButton
¿Le puedes agregar un borde gris sobre el botón verde? Así como los que dividen las enfermedades. 

![image](https://github.com/user-attachments/assets/1185e8c1-56e3-4e89-90b7-e6907d3b6a80)

2024-08-26 00:18 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Psichiatric/index.jsx
> +										paddingTop: "2rem",
A cada titulo de la condición antes de los radio buttons. ¿Le puedes poner paddingTop de 1 rem? Ya que se ve medio raro mucho espacio arriba.

2024-08-26 14:10 UTC, ElrohirGT requested changes
Cuando navego a tu vista desde la aplicación falla con esto:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/540607db-c638-4bc2-8403-372e3ca3931c">

También falla en el storybak
<img width="1088" alt="image" src="https://github.com/user-attachments/assets/bcffaa3c-79bb-4c73-b580-9b0704acf9d2">

2024-08-28 02:24 UTC, lemoonchild approved these changes
autorizo

2024-08-28 02:27 UTC, ElrohirGT approved these changes
**Gótica culona approves.jpg**

2024-08-28 02:27 UTC, merged