fix: patient general data refactoring
SanitasUVG/Sanitas pull request #193
Opened 2024-08-25 02:00 UTC by ElrohirGT

# Jira

[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-237)

## Descripción

Esta PR refactoriza varios endpoints y puntos clave de la UI para el la actualización de datos generales de un paciente. En general debería de mejorar la estabilidad y la estética.

El archivo nix se tocó debido  a que se actualizaron algunas librerías, algunas versiones más nuevas de sam-cli tienen bugs, así que se retrocedió a la LTS.

## Tasks

- \[x] Asignate a tí mismo dentro de la PR.
- \[x] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x] Agrega el link al issue de Jira.
- \[x] Asegurate que la PR pase todos los chequeos de CI.
- \[x] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-08-27 18:07 UTC, lemoonchild requested changes
Cambios en el frontend: 

---------------------------------------------------------------------------------------------------
Me gustaría que hubiera menos padding entre el label y el input. 

![image](https://github.com/user-attachments/assets/c3d783ab-4d3f-46ce-81ca-ea069d0206c9)


Menos espacio para el rojo y más espacio para el anaranjado. 

Además, si le puedes poner un heigth de 3 rem a los base inputs estaría god, pq así lo tienen la mayoría de antecedentes. También si le puedes subir solo un poquito al largo. 
-----------------------------------------------------------------------------------

Si puedes poner el dropdown de lo de sangre al mismo largo que los demás estaría god para quede todo desalineado 

---------------------------------------------------------------------------------------------------
En el JSON me sale insuranceId: 1 pero en el front me aparece en blanco 

![image](https://github.com/user-attachments/assets/41e10348-1fb6-4829-ba01-58bec3191014)

![image](https://github.com/user-attachments/assets/fd43e225-5159-43cf-81a4-cf3a1b35d601)

---------------------------------------------------------------------------------------------------
El mismo espacio que tiene arriba debería de tener abajo owo

![image](https://github.com/user-attachments/assets/bf74f7fa-b7f8-494a-aa3f-3518c91a49d6)

---------------------------------------------------------------------------------------------------
El cosito de contactos debería de tener un bordecito verde así como en el figma

![image](https://github.com/user-attachments/assets/5af9f0b2-f5a2-444d-8098-51c63f5026df)

También los ":" después de cada label del input. "Nombre de contacto: " 

Y también creo que debería de ser un poquito más largo para que así no le tenga que dar a editar para ver el nombre completo o para que se logren ver los primeros dos nombres y el apellido (a menos que sea un rarito de 3 nombres) 

---------------------------------------------------------------------------------------------------

Creo que esto es por el momento je

2024-08-27 18:09 UTC, XavierLopez25 approved these changes
Todo bien pa 🚬🗿

2024-08-27 18:09 UTC, XavierLopez25 commented
Ahí le das update branch ✅

2024-08-27 21:33 UTC, ElrohirGT commented
> En el JSON me sale insuranceId: 1 pero en el front me aparece en blanco

No logré reproducir esto, cómo le hiciste para que saliera así? Tipo qué endpoint llamas o cómo? Porque a mí si me sale así ve:
<img width="1061" alt="image" src="https://github.com/user-attachments/assets/30f379e7-8a51-4cb2-8d8e-5d155acfb97e">

2024-08-28 01:28 UTC, lemoonchild commented
> > En el JSON me sale insuranceId: 1 pero en el front me aparece en blanco
> 
> No logré reproducir esto, cómo le hiciste para que saliera así? Tipo qué endpoint llamas o cómo? Porque a mí si me sale así ve: <img alt="image" width="1061" src="https://private-user-images.githubusercontent.com/45268815/361988272-30f379e7-8a51-4cb2-8d8e-5d155acfb97e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDg1MjgsIm5iZiI6MTcyNDgwODIyOCwicGF0aCI6Ii80NTI2ODgxNS8zNjE5ODgyNzItMzBmMzc5ZTctOGE1MS00Y2IyLThkOGUtNWQxNTVhY2ZiOTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDAxMjM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhOWU2NjFjZTJmOWQ5YjVhNzIzOTkzOTNiNzg5MDIxNjkxMWY5NGVkMTc2M2JiNTRjNWI2ZDRiZTYwMTE5OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9p2oyxOKwk8-qdkbpgWSgqfId0u8pKXFS8Cyc-HP-q4">

mmmm que raro entonces pq a mi me sale en blanco, tal vez mandé a llamar mal el JSON. 

![image](https://github.com/user-attachments/assets/b3cc294f-3274-4f5d-a5c4-da5eb476a4b7)

2024-08-28 02:13 UTC, lemoonchild requested changes
Los cambios también aplicarían aquí de lo del width y el heigth. 

![image](https://github.com/user-attachments/assets/359b4d7c-2ef2-4ca4-93f0-1e0dd61d755a)

Y lo que mencionamos del espacio arriba y abajo.

2024-08-28 02:13 UTC, lemoonchild commented on sanitas_frontend/src/views/UpdateGeneralInformationView/index.jsx
> +		height: "3rem",
¿Podrías agregar: width: "90%"? Y para el dropdown también je.

2024-08-28 02:55 UTC, lemoonchild approved these changes
autorizo 

![image](https://github.com/user-attachments/assets/0a12eb3a-1bd5-44a5-84ef-f26779f49018)

2024-08-28 02:56 UTC, merged