feat: update and cancel personal view
SanitasUVG/Sanitas pull request #196
Opened 2024-08-25 23:12 UTC by BiancaCalderon

# Jira

[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-243?atlOrigin=eyJpIjoiZGFlYjMyMzU0ZTdiNGM0YWI3YTEzYTcxN2IwNWIzOWIiLCJwIjoiaiJ9)

## Descripción

## Tasks

- [ ] Asignate a tí mismo dentro de la PR.
- [ ] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] Añade una breve descripción de la escencia de tus cambios en tu PR.
- [ ] Agrega el link al issue de Jira.
- [ ] Asegurate que la PR pase todos los chequeos de CI.
- [ ] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-08-25 23:54 UTC, lemoonchild requested changes
En general lo veo bien, pero hay ciertos cambios, al hacer upate me deja enviar datos vacíos, tipo, borrar todo:

![Uploading image.png…]()

Pero es bug de la página de por si, permite guardar elementos vacíos ¿Podrías agregar lo del toast? 

Y segundo ¿Le puedes poner un padding top de 3 rem? Y lo del estilo del dropdown de año para la enfermedad de Infarto Agudi de Miocardio. 

Lo demás creo que anda bien.

2024-08-25 23:54 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Personal/index.jsx
> +											<div style={{ display: "flex", gap: "1rem" }}>
En esta parte un paddingTop de 3rem.

2024-08-25 23:54 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Personal/index.jsx
>  										options={yearOptions}
Y aprovechando, le puedes poner estilos a esto? Un width de 90%. 

style={{
								container: { width: "90%" },
								select: {},
								option: {},
								indicator: {},
							}}

2024-08-28 00:47 UTC, ElrohirGT reviewed
![Meme](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSGC_m18lUncQz7aCa-gJyjJAQNljhXmrhhA&s)

Aprobao de mi parte, solo que la autorize Madeline también

2024-08-28 00:47 UTC, ElrohirGT approved these changes

2024-08-28 01:23 UTC, lemoonchild requested changes

2024-08-28 01:23 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Personal/index.jsx
> +			toast.info("Complete todos los campos requeridos.");
Sería un toast.error pq queda raro que sea azul

2024-08-28 01:23 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Personal/index.jsx
> -							readOnly={!addingNew}
aquí si sería adding new pq permite editar el dropdown cuando edito

2024-08-28 01:23 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Personal/index.jsx
> +											<div style={{ display: "flex", gap: "3rem" }}>
el gap está muy grande, es de "1rem", lo que era de "3rem" era el padding top je

2024-08-28 02:16 UTC, lemoonchild approved these changes
autorizo

2024-08-28 02:16 UTC, merged