feat: student surgery history
SanitasUVG/Sanitas pull request #197
Opened 2024-08-26 21:45 UTC by m0rtega

# Jira

[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-231)

## Descripción

Esta tarea contempla cambiar la navegación para que muestre las pantallas correctas dependiendo de si es un paciente o doctor. Además de la implementación de la primera vista para el formulario de paciente.

Validación en endpoint pendiente aún.

## Tasks

- \[x\] Asignate a tí mismo dentro de la PR.
- \[x\] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x\] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x\] Agrega el link al issue de Jira.
- \[x\] Asegurate que la PR pase todos los chequeos de CI.
- \[x\] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-08-26 21:48 UTC, ElrohirGT commented
La PR la veo joya del lado técnico solo faltan los linters y 2 integration tests que revisen la autorización. Básicamente serían estos dos adaptados a tu endpoint.

https://github.com/SanitasUVG/Sanitas/blob/01817343471d6d7b0d5d9911a39d64a407880202/sanitas_backend/src/handlers/UpdatePatient/update-patient.integration.test.mjs#L79-L105

2024-08-28 02:59 UTC, BiancaCalderon requested changes
![image](https://github.com/user-attachments/assets/9b658b90-5c88-4709-831b-e0a045c22e4b)
la página debería mostrarse como responsive, el scroll de abajo no es necesario

2024-08-28 18:46 UTC, ElrohirGT requested changes
Al iniciar sesión cuando el backend todavía no se ha levantado la aplicación peta. En su lugar debería de mostrar un mensaje de error.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/ab9e35dc-bdb8-48df-bdca-08666c43eb2b">

Después de eso lo veo bien en general, lo más probable es que salgan varios bugs cuando ya lo integre con mi parte pero los bugs los arreglamos el siguiente sprint.

2024-08-29 00:07 UTC, lemoonchild requested changes
La página de welcome view tiene problemas al verse en algunas resoluciones: 

![image](https://github.com/user-attachments/assets/a9395804-338d-4d14-9a64-cec778f1a836)

![image](https://github.com/user-attachments/assets/eab0ed75-59ab-4825-a255-c2ec67df66dc)

Y el botón debería de tener más padding en la parte superior.

2024-08-29 01:23 UTC, BiancaCalderon requested changes
![image](https://github.com/user-attachments/assets/d9457830-987d-4b38-b572-46c70cba5c1d)
No logro observar el dropdown del año
![image](https://github.com/user-attachments/assets/ef903ba5-f622-46a6-89dd-56a1794110e0)
No me permite guardar la ficha

2024-08-29 19:23 UTC, ElrohirGT commented
Todos los bugs que se mencionaron por acá se van a arreglar en sprints posteriores. Por ahora se necesita darle merge para poder continuar con la experiencia del usuario que inicia sesión por primera vez.

2024-08-29 19:23 UTC, merged