feat: login & register UI was fixed with error handlers and UI design
SanitasUVG/Sanitas pull request #205
Opened 2024-09-04 05:08 UTC by DanielDubon

# Jira

[Link al issue en Jira](Link%20al%20clickup)

## Descripción

## Tasks

- \[ \] Asignate a tí mismo dentro de la PR.
- \[ \] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[ \] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[ \] Agrega el link al issue de Jira.
- \[ \] Asegurate que la PR pase todos los chequeos de CI.
- \[ \] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-09-04 16:14 UTC, ElrohirGT requested changes

2024-09-04 16:14 UTC, ElrohirGT commented on sanitas_frontend/src/views/RegisterView/index.jsx
Te faltó manejar el error en el que la contraseña no es lo suficientemente fuerte!

2024-09-05 03:21 UTC, ElrohirGT requested changes

2024-09-05 03:21 UTC, ElrohirGT commented on sanitas_frontend/src/views/RegisterView/index.jsx
> +				} else if (response.errorCode === "InvalidPasswordException") {
Estos .errorCode no funcionan realmente pues la propiedad es fumada.

Usa la documentación de axios y la tab de Network del inspector para ver qué chequeos se deben realizar para ver si falla con `InvalidPasswordException`

2024-09-06 17:56 UTC, ElrohirGT requested changes

2024-09-06 17:56 UTC, ElrohirGT commented on sanitas_frontend/src/views/RegisterView/index.jsx
> +			setRegisterResource(
No sirve :v. Lo que hice para probarlo fue modificar los archivos de Cognito y Router para que llamen a las funciones de producción.

Podes hacer lo mismo solamente no les vayas a dar commit.

https://files.fm/u/zmj9jeqey3

2024-09-06 18:50 UTC, lemoonchild reviewed
Autorizo los estilos, gracias por arreglarlos, no le doy aprove porque capaz se hace merge y aún faltan los cambios de Flavio JAJAJA

2024-09-07 01:07 UTC, ElrohirGT approved these changes

2024-09-07 01:11 UTC, merged