feat: added non pathological view to students
SanitasUVG/Sanitas pull request #208
Opened 2024-09-04 19:06 UTC by lemoonchild

# Jira

[Link al issue en Jira](Link%20al%20clickup)

## Descripción

Se añadió la vista de paciente del antecedente no patológico. 

## Tasks

- \[x] Asignate a tí mismo dentro de la PR.
- \[x] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x] Agrega el link al issue de Jira.
- \[x] Asegurate que la PR pase todos los chequeos de CI.
- \[x] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-09-17 15:18 UTC, ElrohirGT requested changes
Hay varias cosas que se cambiaron que no sé por qué lo hicieron la verdad. Me parece nice el uso de `useMemo` es un hook que no conocía!

Recuerden usar siempre la API que ya está asegurada y también usar el hook de la store para el id, además de los otros comentarios que les puse...

2024-09-17 15:18 UTC, ElrohirGT commented on sanitas_backend/template.yaml
> +            Method: POST
Tenés que usar la !Ref para que utilice la API que sí está asegurada!

2024-09-17 15:18 UTC, ElrohirGT commented on sanitas_backend/template.yaml
> -            RestApiId: !Ref SanitasAPI
Por qué se lo quitaron?

2024-09-17 15:18 UTC, ElrohirGT commented on sanitas_frontend/src/views/History/Students/StudentNonPathological/index.jsx
> +	const id = 1;
??? Esto es solo para testear, en realidad debería ser la de arriba!

2024-09-17 15:18 UTC, ElrohirGT commented on sanitas_backend/src/handlers/UpdateStudentNonPatologicalHistory/update-student-nonpatological-history-patient.mjs
> +		const itsDoctor = await isDoctor(client, email);
Esta función puede dar error! Por eso en las otras veces que se usa se le chequea el `.error`!

2024-09-17 15:18 UTC, ElrohirGT commented on sanitas_backend/src/handlers/UpdateStudentNonPatologicalHistory/update-student-nonpatological-history-patient.mjs
> +				await client.query("rollback");
Aquí haces rollback pero nunca ví que iniciaras una transacción! Para guiarte puedes ver el endpoint de datos generales y cómo usa la función `transaction`

2024-09-17 15:35 UTC, XavierLopez25 commented on sanitas_backend/template.yaml
> -            RestApiId: !Ref SanitasAPI
![image](https://github.com/user-attachments/assets/365c162b-557a-4181-a150-df434851e9d4)

Pensé que no tenía que llevar porque ninguno de los endpoints de estudiantes tiene XD

2024-09-17 15:38 UTC, ElrohirGT commented on sanitas_backend/template.yaml
> -            RestApiId: !Ref SanitasAPI
*FUCKING DIES*

Fok, esos también deberían de llevar

2024-09-17 15:39 UTC, XavierLopez25 commented on sanitas_backend/template.yaml
> -            RestApiId: !Ref SanitasAPI
Ahi se los agrego XDD

2024-09-17 15:57 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Students/StudentNonPathological/index.jsx
> +	const id = 1;
Se me fue, bromita

2024-09-23 16:01 UTC, ElrohirGT requested changes

2024-09-23 16:01 UTC, ElrohirGT commented on sanitas_backend/src/handlers/UpdateStudentNonPatologicalHistory/update-student-nonpatological-history-patient.mjs
> +					return responseBuilder
Esto anda mal, como podes ver si querés retornar una response tenés que hacerlo así (el responding with se lo podes quitar si querés porque ya lo usas abajo):
https://github.com/SanitasUVG/Sanitas/blob/ccd5ad29e43fe38e3a024d78ddd82f71d7d5eb50/sanitas_backend/src/handlers/UpdateStudentPersonalHistory/update-student-personal-history-patient.mjs#L95-L104

2024-09-24 01:00 UTC, ElrohirGT approved these changes

2024-09-24 01:01 UTC, merged