feat: view from student personal added
SanitasUVG/Sanitas pull request #209
Opened 2024-09-06 04:33 UTC by BiancaCalderon

# Jira

[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-267?atlOrigin=eyJpIjoiMDE3MzBkNDk0Mzk4NDhkN2FlYjc3MjZjNDFiZjhkOWMiLCJwIjoiaiJ9)

## Descripción

## Tasks

- \[ \] Asignate a tí mismo dentro de la PR.
- \[ \] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[ \] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[ \] Agrega el link al issue de Jira.
- \[ \] Asegurate que la PR pase todos los chequeos de CI.
- \[ \] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-09-07 00:17 UTC, lemoonchild requested changes

2024-09-07 00:17 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Students/StudentPersonal/index.jsx
> +					paddingLeft: "2rem",
¿Le puedes eliminar esto?

2024-09-07 00:17 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Students/StudentPersonal/index.jsx
> +			</div>
Esto también ya que es el dashboard owo

2024-09-07 00:17 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Students/StudentPersonal/index.jsx
> +							¿Usted ha sido diagnosticado por un médico con una de las
Esto sería de separarlo en dos. 

`<h3
							style={{
								fontFamily: fonts.textFont,
								fontWeight: "normal",
								fontSize: fontSize.subtitleSize,
								paddingTop: "0.7rem",
								paddingBottom: "0.2rem",
							}}
						>
							asdkjasdjkajdas 
						</h3>
						<h3
							style={{
								fontFamily: fonts.textFont,
								fontWeight: "normal",
								fontSize: fontSize.subtitleSize,
								paddingBottom: "3rem",
							}}
						>
							Por favor ingrese un elemento por diagnóstico.
						</h3>`

2024-09-07 00:17 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Students/StudentPersonal/index.jsx
> +			const response = await updateStudentPersonalHistory(
Aqui te va a dar error, estas pasando dos datos y la función que tienes en el data layer recibe 3, lo que te requiendo es tomar como base el de update normal de las doctoras y solo cambiar la ruta para tu endpoint, ya que debería dar lo mismo, ya que aquí guardas un JSON en otro JSON y anda que explota.

2024-09-07 01:40 UTC, lemoonchild requested changes
![image](https://github.com/user-attachments/assets/22728381-39a8-4dab-aee9-38642db8d4d7)

Tampoco deja guardar cosas.

2024-09-07 01:40 UTC, lemoonchild commented on sanitas_frontend/src/dataLayer.mjs
> +/**
Lo agregaste dos veces je

2024-09-07 01:40 UTC, lemoonchild commented on sanitas_frontend/src/dataLayer.mjs
> +	const url = `${PROTECTED_URL}/student/student-personal-history`;
La ruta que tienes en el template.yalm es diferente

2024-09-12 23:34 UTC, ElrohirGT submitted a review, later dismissed

2024-09-12 23:35 UTC, ElrohirGT commented
De mi parte ya anda!

2024-09-13 00:47 UTC, ElrohirGT approved these changes

2024-09-13 00:48 UTC, merged