fix: removed update button from studentsurgical
SanitasUVG/Sanitas pull request #210
Opened 2024-09-07 00:26 UTC by m0rtega

# Jira

[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-231)

## Descripción

## Tasks

- \[ \] Asignate a tí mismo dentro de la PR.
- \[ \] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[ \] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[ \] Agrega el link al issue de Jira.
- \[ \] Asegurate que la PR pase todos los chequeos de CI.
- \[ \] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-09-07 01:21 UTC, lemoonchild requested changes
¿Podrías cambiar dos cosas? 

![image](https://github.com/user-attachments/assets/b848bb5c-0ccb-499f-8b88-0e589dc40587)
Quitar el paddingLeft de la línea 62 

Y en la parte de arriba: 
![image](https://github.com/user-attachments/assets/38739fe1-b914-4c95-822c-6897641b6259)

Tiene que ir este mensaje 

Sería algo así: 
<h3 style={{ fontFamily: fonts.textFont, fontWeight: "normal", fontSize: fontSize.subtitleSize, paddingTop: "0.7rem", paddingBottom: "0.2rem", }} > asdkjasdjkajdas  </h3> <h3 style={{ fontFamily: fonts.textFont, fontWeight: "normal", fontSize: fontSize.subtitleSize, paddingBottom: "3rem", }} > Por favor ingrese un elemento por diagnóstico. </h3>


![Uploading image.png…]()

En esta parte

2024-09-10 03:44 UTC, ElrohirGT reviewed
De mi parte todo joya, solo arregla lo que @lemoonchild te dejó jaja

2024-09-14 04:40 UTC, ElrohirGT commented
<img width="743" alt="image" src="https://github.com/user-attachments/assets/3bb7dd79-837d-492e-8b9d-3ec9296d7a6c">

![](https://i.imgflip.com/4gfk8d.png?a479184)

2024-09-19 23:19 UTC, lemoonchild approved these changes
De mi parte lo veo bien owo

2024-09-19 23:20 UTC, merged