feat: student traumatological view
SanitasUVG/Sanitas pull request #214
Opened 2024-09-15 06:28 UTC by m0rtega

# Jira

[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-250)

## Descripción

Implementación de la vista para el formulario de paciente para antecedentes traumatológicos.

## Tasks

- \[x\] Asignate a tí mismo dentro de la PR.
- \[x\] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x\] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x\] Agrega el link al issue de Jira.
- \[x\] Asegurate que la PR pase todos los chequeos de CI.
- \[x\] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-09-15 19:46 UTC, ElrohirGT requested changes
De lado de los estilos lo veo bien. Pero esta raro porque aunque me dice que hace el post y el backend no falla, los datos no se insertan! Literalmente recargo la página y no me sale nada!


https://github.com/user-attachments/assets/d63ab938-e407-41f0-a8ab-e570b27779ea

Se supone que si está bien insertado, el GET devuelve el valor que acabo de ingresar, así que algo estás haciendo mal ahí que aunque la request no falla, no se inserta bien. Creo que tiene que ver con lo de la transacción...

2024-09-15 19:46 UTC, ElrohirGT commented on sanitas_backend/src/handlers/UpdateStudentTraumatologicalHistory/update-student-traumatological-history-patient.mjs
> +	const responseBuilder = createResponse().addCORSHeaders("PUT");
Acá usas PUT! Pero el método es POST!

2024-09-15 19:46 UTC, ElrohirGT commented on sanitas_backend/src/handlers/UpdateStudentTraumatologicalHistory/update-student-traumatological-history-patient.mjs
> +		await client.query("begin");
Usas begin para una transacción pero nunca haces commit o rollback!

Implementando mi vista me hice un wrapper! Cuando le den merge a mi PR lo vas a poder usar jaja

2024-09-17 15:26 UTC, ElrohirGT requested changes

2024-09-17 15:26 UTC, ElrohirGT commented on sanitas_backend/src/handlers/UpdateStudentTraumatologicalHistory/update-student-traumatological-history-patient.mjs
> +		await client.query("rollback");
Lo malo de tener el rollback acá es que cualquier error de arriba que se de antes de hacer "begin" hará un rollback! Y si se da un rollback sin iniciar una transacción entonces dará error...

Si querés nos juntamos hoy en la clase del yapper a ver cómo se arreglaría esto...

2024-09-18 17:03 UTC, ElrohirGT requested changes
Arreglale el bugaso que vimos ayer, y ya saldría

2024-09-23 17:19 UTC, ElrohirGT requested changes
sigue muriendo...

Lo que probé hacer fue agregar un antecedente y después agregar otro, y murió:
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/e828da7b-8539-4ac1-b997-493d75b348b9">

2024-09-24 05:09 UTC, lemoonchild commented
> sigue muriendo...
> 
> Lo que probé hacer fue agregar un antecedente y después agregar otro, y murió: <img alt="image" width="1552" src="https://private-user-images.githubusercontent.com/45268815/369980973-e828da7b-8539-4ac1-b997-493d75b348b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNTQ4MjIsIm5iZiI6MTcyNzE1NDUyMiwicGF0aCI6Ii80NTI2ODgxNS8zNjk5ODA5NzMtZTgyOGRhN2ItODUzOS00YWMxLWI5OTctNDkzZDc1YjM0OGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA1MDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNGFhZjJmYjcxNzM2OGNlODE5ZTg4OTEwNzk0MTRhZWY4ZTcwMzYzYzI1N2ZhN2UxNzA3OTMxMjNmYjM4NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MetaWvZ1WM1eYxTJex0OpHI_KfmJbpdg9ZB-x9F5chk">

¿No será problema de como manda la información? A mi me pasaba que terminaba haciendo doble wrap de la info al enviarla.

2024-09-24 16:26 UTC, m0rtega commented
> > sigue muriendo...
> > Lo que probé hacer fue agregar un antecedente y después agregar otro, y murió: <img alt="image" width="1552" src="https://private-user-images.githubusercontent.com/45268815/369980973-e828da7b-8539-4ac1-b997-493d75b348b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNTQ4MjIsIm5iZiI6MTcyNzE1NDUyMiwicGF0aCI6Ii80NTI2ODgxNS8zNjk5ODA5NzMtZTgyOGRhN2ItODUzOS00YWMxLWI5OTctNDkzZDc1YjM0OGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA1MDg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNGFhZjJmYjcxNzM2OGNlODE5ZTg4OTEwNzk0MTRhZWY4ZTcwMzYzYzI1N2ZhN2UxNzA3OTMxMjNmYjM4NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MetaWvZ1WM1eYxTJex0OpHI_KfmJbpdg9ZB-x9F5chk">
> 
> ¿No será problema de como manda la información? A mi me pasaba que terminaba haciendo doble wrap de la info al enviarla.

Vimos y era más un problema de tener que cambiar el token del usuario cuando cambiaba de vista del doctor y del paciente.

2024-09-25 02:20 UTC, ElrohirGT approved these changes

2024-09-25 02:20 UTC, merged