feat: responsive for login and register view
SanitasUVG/Sanitas pull request #238
Opened 2024-10-03 01:10 UTC by DanielDubon

# Jira

[Link al issue en Jira](Link%20al%20clickup)

## Descripción

## Tasks

- \[ \] Asignate a tí mismo dentro de la PR.
- \[ \] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[ \] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[ \] Agrega el link al issue de Jira.
- \[ \] Asegurate que la PR pase todos los chequeos de CI.
- \[ \] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-10-03 23:24 UTC, lemoonchild requested changes
![image](https://github.com/user-attachments/assets/eab0aa85-0445-47d3-bdf2-798249b7081b)
De mi parte me gustaría que el mismo padding que tiene arriba del logo tenga debajo je. En ambas páginas. 

![image](https://github.com/user-attachments/assets/727e2bc5-dbd7-4ca4-bf31-ba87c3d0f7b2)

Y el "Ingresa tus datos" está mejor con 1.06rem de font-size, ya que se ve muy pequeño.

2024-10-05 01:01 UTC, ElrohirGT submitted a review, later dismissed

2024-10-07 16:41 UTC, lemoonchild requested changes
Solo el cambio de la fuente, lo demás ya está.

2024-10-07 16:41 UTC, lemoonchild commented on sanitas_frontend/src/views/LoginView/index.jsx
> +								fontSize: isMobile ? "0.85rem" : fontSize.subtitleSize,
Me vas a matar, pero faltó este cambio jasj trata de ponerlo a 1.06rem

2024-10-09 01:15 UTC, lemoonchild approved these changes
autorizo

2024-10-09 01:15 UTC, merged