feat: responsive fam view
SanitasUVG/Sanitas pull request #247
Opened 2024-10-05 13:56 UTC by BiancaCalderon

# Jira

[Link al issue en Jira](Link%20al%20clickup)

## Descripción

## Tasks

- \[ \] Asignate a tí mismo dentro de la PR.
- \[ \] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[ \] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[ \] Agrega el link al issue de Jira.
- \[ \] Asegurate que la PR pase todos los chequeos de CI.
- \[ \] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-10-07 16:09 UTC, ElrohirGT submitted a review, later dismissed

2024-10-07 16:09 UTC, ElrohirGT commented on sanitas_frontend/src/views/History/Students/StudentPersonal/index.jsx
> +	}, []);
Igual que con la otra vista, por favor usa el hook de useWindowSize :)

2024-10-07 16:55 UTC, lemoonchild requested changes
![image](https://github.com/user-attachments/assets/c106ee3a-e2d0-433c-b1e1-6254be7d5e3c)

Aquí lo mismo, que el contenedor llegue hasta abajo, así como en la versión web 

![image](https://github.com/user-attachments/assets/7ec08232-e53f-4cdd-8a7d-b882f34971e2)

También trata de que el contenedor llegue hasta abajo 

Para los estilos: 
![image](https://github.com/user-attachments/assets/077038d8-11e3-43d4-88ec-9a60a7a73824)

El padding del contenedor principal para los elementos que se llena dejalo en 1 rem 
Y lo de los botones, están muy separados

2024-10-07 16:55 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Students/StudentPersonal/index.jsx
> +				padding: isMobile ? "0.5rem" : "1rem",
En este, 1rem para ambos está mejor.

2024-10-10 16:46 UTC, ElrohirGT reviewed
De mi parte approve! solo que te revise Madeline los estilos...

2024-10-11 01:40 UTC, lemoonchild requested changes
Hay mucho espacio entre el subitutlo y los elementos 

![image](https://github.com/user-attachments/assets/0b7d43cc-04f1-4514-b25f-9e98a08540ed)

Creo que es algo que está creando el espacio entre ellos ya que al quitarle el paddingBottom al subtitulo sigue teniendo espacio lo cual anda raro, sería de que revises eso. 

Ya que así se ve con el paddingBottom: 
![image](https://github.com/user-attachments/assets/5df8908b-223a-4d65-b193-8269e7dc3450)

Y así si se lo quito: 
![image](https://github.com/user-attachments/assets/a13c7e80-525b-483a-85d5-4eb717a0a48e)

Un problema de quitar el paddingBottom a la brava es que el otro contenedor se queda sin espacio. 

![image](https://github.com/user-attachments/assets/3f71ab64-d926-4d65-9625-3b701fbf3417)

O sería de revisar que crea el espacio y arreglarlo o quitarle el paddingBottom en móvil (en web tal vez dejarlo en 1.5rem ya que no afecta mucho) y colocarle paddingTop al contenedor que tiene lo de los inptus (solo en móvil) para que no tenga mucho problema. 

------------------------------------------------------------------------------

El botón de guardar debería ser así: 

![image](https://github.com/user-attachments/assets/374c2072-13b2-4e43-9465-03c34dec0fab)

En las dos versiones se ve igual de apachado, ¿Lo podrías poner en altura de 3rem por favor? 

------------------------------------------------------------------------------
Estos input se ven muy pequeños, la verdad no ando segura por qué se ven así si anda igual el código que familiares, sería de revisar eso. 

Ya que así se ve en personales:
![image](https://github.com/user-attachments/assets/25f0a94c-c3fe-40c5-95f2-5f30f1edaf90)

Y así en familiares:

![image](https://github.com/user-attachments/assets/d480d381-485c-4e0e-8351-a632e38c4281)
 
 ------------------------------------------------------------------------------

Lo demás lo veo bastante bien, solo serían esos cambios

2024-10-11 04:08 UTC, lemoonchild approved these changes
autorizo

2024-10-11 04:08 UTC, merged