feat: familiar responsive view
SanitasUVG/Sanitas pull request #248
Opened 2024-10-05 14:07 UTC by BiancaCalderon

# Jira

[Link al issue en Jira](Link%20al%20clickup)

## Descripción

## Tasks

- \[ \] Asignate a tí mismo dentro de la PR.
- \[ \] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[ \] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[ \] Agrega el link al issue de Jira.
- \[ \] Asegurate que la PR pase todos los chequeos de CI.
- \[ \] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-10-07 16:04 UTC, ElrohirGT requested changes
Además del que te puse por el useEffect. No sé si deba verse así en movil? Sería de que Madeline te confirme los estilos...
<img width="537" alt="image" src="https://github.com/user-attachments/assets/ea4256b7-477b-4017-b63e-9501f1a295c3">

2024-10-07 16:04 UTC, ElrohirGT commented on sanitas_frontend/src/views/History/Students/StudentFamiliar/index.jsx
> +	const [windowWidth, setWindowWidth] = useState(window.innerWidth);
Ya hay un hook que hace esto! Se llama `useWindowSize` te retorna cabal un objeto que tiene un width y un height! Así borras el useEffect y todo eso.

2024-10-07 16:49 UTC, lemoonchild requested changes
![image](https://github.com/user-attachments/assets/d11098b4-46ef-4afb-97c6-72643d45eb4d)

Cuando muestre el estado de error hay que colocar el contenedor hasta abajo owo

![image](https://github.com/user-attachments/assets/c45031ce-a2ab-48a6-bc93-e2e2a2e25893)
 
En esta parte también, hay que hacer que el contenedor cubra hasta abajo 

De parte de los estilos: 
![image](https://github.com/user-attachments/assets/8cae9fc2-4237-4084-95a1-dbf673d10b84)
El padding del contenedor dejalo a 1 rem (el contenedor que tiene el border 1px solid etc.., el que contiene lo de llenar las cosas. 

![image](https://github.com/user-attachments/assets/c2f248d8-cd8c-42ee-ab58-4eb3807a6466)

Los botones andan muy separados ajksdjk trata de unirlos un poco más.

2024-10-08 23:12 UTC, lemoonchild requested changes
También si puedes hacer lo de los botones que mencionó flavio, que quedaría mejor uno sobre otro

De esto: 
![image](https://github.com/user-attachments/assets/0ab34f07-21c9-4a9e-bae5-4b5a4f404003)

A esto: 
![image](https://github.com/user-attachments/assets/6a1db33f-9cf8-4f5d-9dad-58935e5b5b2a)

En esta línea: 
![image](https://github.com/user-attachments/assets/8885f1db-6c1b-4fe4-b6ee-b55465fcfe3b)
Cambia de 0.5 en mobile a 1rem, ya que en el padding que tienes del innerContainer lo reescribe y queda como 1rem 1rem 1rem 0.5rem kajsdkja y debería de ser 1rem todo.

2024-10-08 23:12 UTC, lemoonchild commented on sanitas_frontend/src/views/History/Students/StudentFamiliar/index.jsx
> +				textAlign: isMobile ? "center" : "left",
Aquí anda al revés, es "left" : "center", ya que tanto el titulo como subtitutlo ya no andan al centro. 

![image](https://github.com/user-attachments/assets/64804b60-10ea-4dde-9cd1-1c8deeed93ef)

2024-10-09 01:31 UTC, lemoonchild requested changes
Lo de minheight a height era solo en esa línea kjasdkj lo demás anda bien como estaba. 

![image](https://github.com/user-attachments/assets/8f1ba5d4-6fc4-4c4c-b229-06885e6275f8)

Y en lo de los botones, no sé si es posible que copies los estilos de Flavio en alérgicos, así tenemos el mismo diseño 

![image](https://github.com/user-attachments/assets/07f7f10a-e7d2-4922-86a6-8cf156e58b94)

2024-10-09 19:08 UTC, lemoonchild requested changes
Solo una cosa, este: 

![image](https://github.com/user-attachments/assets/45bbabfd-5452-443b-b12c-c8b4a4039b88)

Debería de verse como este: 

![image](https://github.com/user-attachments/assets/3365e2de-003a-4c55-ba4b-88f213023698)

Si es posible revisa que hizo Flavio para eso JAJA ya que saqué el ejemplo de antecedentes alérgicos. 

------------------------------------------------------------------------------------------------------------

Y la fuente de los botones se ve algo grande, para mobil trata de que quede en: 0.875rem, Flavio lo tiene así entonces puedes revisar que tal. 

![image](https://github.com/user-attachments/assets/2f6b9d94-6e9e-4e69-b187-8df351a3d729)

------------------------------------------------------------------------------------------------------------

Y otra cosa: 

Para la versión web los input están muy pequeños, tienen que estar al 90% de la página, y el dropdown también al mismo nivel que el input. 

![image](https://github.com/user-attachments/assets/00e5401d-4ad1-4ca1-aad7-761ff8f81169)

------------------------------------------------------------------------------------------------------------

Y estaba notando algo, el coso para  guardar la información sale al revés, está así: 

![image](https://github.com/user-attachments/assets/7cafd399-0e1e-4e28-a904-1e8cda292bac)

Y debería estar así: 

![image](https://github.com/user-attachments/assets/da4da6e6-2534-45d1-8c06-ab3ed4e39847)

Le tienes que dar la vuelta a como estaba antes (este cambio es de la versión web), en la versión mobile si debería de salir arriba del otro (ese ya está, el único cambio es como se ve en la versión web.)

------------------------------------------------------------------------------------------------------------

Y aprovechando, si puedes cambiar el height de los input a 3rem, ya que andan a 2.5rem 

![image](https://github.com/user-attachments/assets/818f83ee-2a4b-4b77-bcf8-47af9de9a5dd)

2024-10-10 02:26 UTC, lemoonchild approved these changes
godd

2024-10-10 02:30 UTC, ElrohirGT approved these changes

2024-10-10 02:30 UTC, merged