feat: mobile version for surgical traumatologic
SanitasUVG/Sanitas pull request #249
Opened 2024-10-07 14:32 UTC by XavierLopez25

# Jira

[Link al issue en Jira](Link%20al%20clickup)

## Descripción

Responsive para vistas de Quirúrigicos/Traumatológicos.

## Tasks

- \[x] Asignate a tí mismo dentro de la PR.
- \[x] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x] Agrega el link al issue de Jira.
- \[x] Asegurate que la PR pase todos los chequeos de CI.
- \[x] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-10-07 15:57 UTC, ElrohirGT requested changes
No sirve tu storybook....
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/8a08e48c-2156-413e-ae53-f72ae63d0dcf">

2024-10-07 16:38 UTC, ElrohirGT reviewed
De mi parte todo joya, solo que Madeline te apruebe los estilos y ya estaríamos!

2024-10-07 16:38 UTC, ElrohirGT commented on sanitas_frontend/src/utils/measureScaling.js
voy a confiar que esto no afecta nada...

2024-10-07 16:39 UTC, ElrohirGT submitted a review, later dismissed

2024-10-08 04:57 UTC, lemoonchild requested changes
![image](https://github.com/user-attachments/assets/55d7332b-6636-4183-a15e-78f0e33e82a9)

En trauma y quirurgicos en la versión web se come el margen abajo. 

![image](https://github.com/user-attachments/assets/e1a68eb3-927f-47ba-b8a6-703ea9c68cb6)

En el place holder del hueso fracturado dejalo en 1.10rem mejor, igual que en el de quirurgicos.

2024-10-08 05:31 UTC, lemoonchild approved these changes
pero no se enoje

2024-10-08 14:09 UTC, merged