feat: gynob mobile view
SanitasUVG/Sanitas pull request #251
Opened 2024-10-08 19:37 UTC by ElrohirGT

# Jira

[Link al issue en Jira](Link%20al%20clickup)

## Descripción

Esta PR añade soporte para móvil a la vista de ginecoobstétricos para pacientes.

## Tasks

- \[x] Asignate a tí mismo dentro de la PR.
- \[x] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x] Agrega el link al issue de Jira.
- \[x] Asegurate que la PR pase todos los chequeos de CI.
- \[x] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-10-08 19:37 UTC, ElrohirGT commented
Todavía no anda para revisar xD

2024-10-08 20:04 UTC, ElrohirGT commented
Ya anda

2024-10-08 22:47 UTC, lemoonchild requested changes
El h3 también hay que centrarlo 
![image](https://github.com/user-attachments/assets/bced5591-4368-4d81-995d-5983cd5eee56)

También si puedes colocarle el borde que tienen todos a este je 
![image](https://github.com/user-attachments/assets/dc70f8b8-884b-43ee-9a6c-5df752eba6f4)

El input de ingresar edad creo que anda muy pequeño:
![image](https://github.com/user-attachments/assets/f90bc96d-44e7-4862-aa16-42c5c7f244ed)

Creo que los inputs y los drowdown de año hay que cambiarlos a width de 100% (la sección de la suma de embarazos anda bien, el cambio es en lo demás)


Estaba viendo que la página no tiene error kjasdjk tipo, no le puse el ID y no me lanza error de que tiene algo. 

tipo anda así: 
![image](https://github.com/user-attachments/assets/9de8fa42-d7ba-4aa9-b49c-dfa887d0d49b)

Y me sale: 
![image](https://github.com/user-attachments/assets/991d0aeb-663e-4f75-b11a-1303a7ebb344)

2024-10-09 01:19 UTC, lemoonchild requested changes
![image](https://github.com/user-attachments/assets/b41c4d51-539f-4208-9c1a-3a225d4e2bab)

Aparece el border mientras se carga JAJJA

2024-10-09 18:51 UTC, lemoonchild approved these changes
autorizada

2024-10-09 18:51 UTC, merged