feat: Added basic export data view
SanitasUVG/Sanitas pull request #290
Opened 2024-10-21 21:20 UTC by ElrohirGT

# Jira

[Link al issue en Jira](Link%20al%20clickup)

## Descripción

Esta PR agrega una vista para exportar todas las visitas en un período de tiempo determinado, por defecto el tiempo es de un mes.

## Tasks

- \[x] Asignate a tí mismo dentro de la PR.
- \[x] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x] Agrega el link al issue de Jira.
- \[x] Asegurate que la PR pase todos los chequeos de CI.
- \[x] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-10-23 02:11 UTC, BiancaCalderon reviewed
![image](https://github.com/user-attachments/assets/264c54b6-d28f-4fd2-98a0-43941b02c65b)

2024-10-23 02:37 UTC, XavierLopez25 requested changes
Probé agregar 3 citas para Juan y 2 que ya están en los `insert.sql`, entonces hay 5 filas en `CONSULTAS`: 
![image](https://github.com/user-attachments/assets/ed98a298-56ca-4877-bb45-063401c6bf76)

También le moví al `REFRESH MATERIALIZED VIEW stats;` y luego exporte los archivos pero únicamente aparece un registro por defecto y es uno de los default sino mal recuerdo, los de Juan no me aparecen:

![image](https://github.com/user-attachments/assets/d83aa76c-30be-4d0d-9ee1-f313cf19c4e2)

Foto:

![image](https://github.com/user-attachments/assets/f08ad9d5-74c4-431f-8e47-2464755c226f)


Cualquier cosa me confirmás para ver si es **skill issue** mío XD

2024-10-23 17:04 UTC, ElrohirGT commented
Al final le puse que el final es EXCLUSIVO y que el inicio es INCLUSIVO.

Por defecto se jala la fecha de manaña

2024-10-25 19:24 UTC, lemoonchild requested changes
Skill issue mío

2024-10-25 20:04 UTC, XavierLopez25 approved these changes
Fino, ya funca

2024-10-25 20:15 UTC, lemoonchild approved these changes

2024-10-25 20:15 UTC, merged