fix: removed edit button
SanitasUVG/Sanitas pull request #298
Opened 2024-10-25 11:59 UTC by m0rtega

# Jira

[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-304)

## Descripción

Datos generales no debería de tener el botón de editar ya que los demás no lo tienen. 

Validación en endpoint pendiente aún.

## Tasks

- \[x\] Asignate a tí mismo dentro de la PR.
- \[x\] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x\] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x\] Agrega el link al issue de Jira.
- \[x\] Asegurate que la PR pase todos los chequeos de CI.
- \[x\] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-10-25 17:49 UTC, ElrohirGT requested changes
No debería dejarme cambiar el carnet de estudiante porque ya tiene datos!

<img width="565" alt="image" src="https://github.com/user-attachments/assets/bde97bb5-8fa5-4082-8c00-11765a9c8222">


Tampoco me debería dejar cambiar el email porque ya tiene datos!
<img width="281" alt="image" src="https://github.com/user-attachments/assets/de4a774b-a696-427b-af16-31ea260c5225">

No me debería dejar ni abrir el popup ya que no tiene que dejarme cambiarlo!
<img width="577" alt="image" src="https://github.com/user-attachments/assets/3b5d195e-f0d1-4820-a991-b4015371780c">

2024-10-25 17:49 UTC, ElrohirGT commented on sanitas_frontend/src/components/StudentDashboardTopBar/index.jsx
> +					marginTop: "12rem",
Me da cringe el margin, pero como tiene position absolute pela.

Para próximas, podrías haber puesto right: "3rem" y top: "12rem" directamente jaja.

2024-10-25 18:36 UTC, ElrohirGT requested changes
Joya! Ya funciona casi todo. Solo veo un error cuando ingreso un paciente nuevo y modifico o modifico algún dato. La fecha de nacimiento deja demostrarse, si cambio de tab y regreso a generales ya aparece pero igual es bugazo.

<img width="337" alt="image" src="https://github.com/user-attachments/assets/efe00c98-60de-41ed-a479-44dece884e09">

2024-10-25 18:57 UTC, ElrohirGT requested changes
xD?


https://github.com/user-attachments/assets/65d051a5-4c26-4a66-bac5-92ec9c8897f5

2024-10-25 19:25 UTC, lemoonchild requested changes
No sé si hay alguna forma de que estos elementos por default se encuentren abiertos jkasdkj 
![image](https://github.com/user-attachments/assets/9e5763ee-8198-4b8e-8813-d926997d4fec)

-----------------------------------------------------------------------------------------------


Me gustaría que todos los botones estén al centro, ya que al lado se ven medio raros
![image](https://github.com/user-attachments/assets/0d167a71-8c3f-45a1-9bc9-80fea3556108)
Y si es posible que tenga un paddingTop de 2rem los botones. 


-----------------------------------------------------------------------------------------------

Faltan los place holder de la sección de contactos del paciente también 

![image](https://github.com/user-attachments/assets/34d4db94-1543-422a-90ff-6b1503209a6d)


-----------------------------------------------------------------------------------------------

No sé si es skill issue mio pero cuando creo el paciente no me sale la fecha de nacimiento 

![image](https://github.com/user-attachments/assets/ab23d49d-8dbb-4918-8000-f6abc06514ac)

-----------------------------------------------------------------------------------------------

Me da error cuando quiero enviar la información 

![image](https://github.com/user-attachments/assets/d912e421-d93f-46e4-a930-7550b1a0c4c3)

2024-10-25 21:09 UTC, ElrohirGT reviewed
De mi parte ya anda joya! Solo que te la apruebe @lemoonchild

2024-10-27 19:09 UTC, lemoonchild approved these changes
autorizo

2024-10-27 19:09 UTC, merged