feat: redesign of database sql code
SanitasUVG/Sanitas pull request #46
Opened 2024-05-15 22:45 UTC by XavierLopez25

# Jira

[Link al issue en Jira](Link%20al%20clickup)

## Descripción

Se resideñó el código SQL de la base de datos, estructura de tablas y de inserts de prueba.

## Tasks

- \[x] Asignate a tí mismo dentro de la PR.
- \[x] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](htxs://www.conventionalcommits.org/en/v1.0.0/).
- \[x] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x] Agrega el link al issue de Jira.
- \[x] Asegurate que la PR pase todos los chequeos de CI.
- \[x] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-05-15 23:17 UTC, ElrohirGT requested changes
En general está bien! Ya te puse algunas correcciones y me gustaría agregar unas cosas:
- Por favor pon de primero siempre los campos de llaves, sean foráneas y especialmente si son primarias.
- Para definir llaves primarias usa siempre la sintaxis de `PRIMARY KEY` dentro de la misma línea.
- Para definir llaves foránea usa la sintaxis:
![image](https://github.com/SanitasUVG/Sanitas/assets/45268815/71322914-a558-466e-880f-8a0a7edf25a3)

2024-05-15 23:17 UTC, ElrohirGT commented on database/tables.sql
> +    APELLIDOS VARCHAR(24),
Los nombres aveces se extienden un montón. Preferiría que fueran por lo menos 50 caracteres por nombres y apellidos

2024-05-15 23:17 UTC, ElrohirGT commented on database/tables.sql
> +);
Recuerda que hay algunos campos que fijo si o sí debemos ingresar, estos deberían estar marcados como Not Null. Son los mismos que están en la historia de usuario del ingreso de la ficha médica.

2024-05-15 23:17 UTC, ElrohirGT commented on database/tables.sql
> +    MOTIVO VARCHAR(100),
Preferiría si el motivo de la consulta fuera un TEXT y también debería de ser NOT NULL porque no tiene sentido que ingresen una consulta sin haber ingresado un motivo primero.

2024-05-15 23:17 UTC, ElrohirGT commented on database/tables.sql
> +    EVALUADOR VARCHAR(50),
Esta es una llave foránea a Usuario.

2024-05-15 23:21 UTC, BiancaCalderon approved these changes

2024-05-16 01:28 UTC, ElrohirGT requested changes
Lo otro que agregaría es que todos los antecedentes deberían tener `NOT NULL` y DEFAULT FALSE en el boolean que indica si tiene o no ese tipo de antecedente.

2024-05-16 01:28 UTC, ElrohirGT commented on database/tables.sql
> +    ID_SEGURO INTEGER NOT NULL,
Puede que el paciente no tenga ningún seguro. En caso no tenga este campo debería de ser NULL

2024-05-16 01:28 UTC, ElrohirGT commented on database/tables.sql
> +    PRESION_DIASTOLICA INTEGER NOT NULL,
Estos datos no siempre los ingresan todos, así que puede que algunos sean null y otros no. Quitales los Not Null

2024-05-16 01:28 UTC, ElrohirGT commented on database/tables.sql
>      TRATAMIENTO VARCHAR(100),
Creo que tratamiento quedaría mejor como TEXT

2024-05-16 01:28 UTC, ElrohirGT commented on database/tables.sql
>      EMAIL VARCHAR(50),
Este también debería ser Not Null

2024-05-16 01:37 UTC, ElrohirGT approved these changes
![image](https://github.com/SanitasUVG/Sanitas/assets/45268815/67856894-7052-453f-ad47-1fb48d9105f6)

2024-05-16 01:42 UTC, merged