feat: added "form" and "check cui" enpoints to add-patient GUI
SanitasUVG/Sanitas pull request #64
Opened 2024-05-23 18:43 UTC by lemoonchild

# Jira

[Link al issue en Jira](https://uvg-team-sanitas.atlassian.net/browse/SCRUM-80?atlOrigin=eyJpIjoiOGQ0M2FjMGIzZmExNDhmZTkzZTJhZDVhODkxNmI0YTMiLCJwIjoiaiJ9)

## Descripción

Se añadió el enpoint realizado por @BiancaCalderon y @DanielDubon al GUI de añadir paciente en base a si existe o no el CUI. 

## Tasks

- \[x] Asignate a tí mismo dentro de la PR.
- \[x] Asegúrate que el nombre de la PR siga el formato de [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- \[x] Añade una breve descripción de la escencia de tus cambios en tu PR.
- \[x] Agrega el link al issue de Jira.
- \[x] Asegurate que la PR pase todos los chequeos de CI.
- \[x] Ponle las tags correspondientes a tu PR.
  Backend: PRs que modifican lógica relacionada al backend.
  Frontend: PRs que modifican lógica relacionada al frontend.
  Database: PRs que modifican lógica relacionada a la base de datos.
  Wiki: PRs que editan la wiki.
  Nix: PRs que modifican el entorno de desarrollo en Nix.
  CI/CD: PRs relacionadas con la CI/CD pipeline.

2024-05-23 23:30 UTC, ElrohirGT requested changes
Por favor separa la función que llama a la API del componente que la utiliza, actualmente está integrada dentro de la vista, esto hace que tenga que tener corriendo el backend para testear la vista, esto no debería ser necesario.

2024-05-24 02:26 UTC, ElrohirGT requested changes

2024-05-24 02:26 UTC, ElrohirGT commented on sanitas_frontend/src/views/AddPatientView/index.jsx
> +import { checkCui, submitPatientData } from "src/dataLayer.mjs";
Estas funciones deben ser pasadas como PROPS a tu vista. Si las usas directamente dentro de tu vista para hacerles mock tenes que usar funciones turbias de vitest.

Recuerda agregarles JSDoc, puedes ver cómo lo hice con mi vista de SearchPatient y cómo maneje lo de JSDoc para no andar repitiendo tipos en varios lugares

2024-05-24 05:04 UTC, ElrohirGT approved these changes

2024-05-24 05:09 UTC, XavierLopez25 approved these changes

2024-05-24 05:10 UTC, merged